server:
  port: 8080
logging:
  level:
    searchengine: debug

spring:
  datasource:
    username: root
    password: Jrcfyf12091995!
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
      show-sql: true

  liquibase:
    change-log: classpath:db/change-log/db.changelog-master.xml
    enabled: true
    drop-first: false

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox.ru
    - url: http://ispu.ru
      name: ИГЭУ
    - url: https://www.stmwater.ru
      name: Доставка Воды
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: http://www.radiomv.ru
#      name: radiomv.ru
    - url: https://sendel.ru
      name: Sendel